### ISSUE TITLE
您好，这项工作只能使用ply进行推理吗？

### ISSUE THREAD

**Issue by ShaneCan** [gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds#1]
使用pcd无法计算出结果

**Comment by gpeihong** [comment]
你好，我具体细节忘了很多。我这个工作只是一个点云对图像的投影和连线的可视化。我是用ply进行处理的。ply和pcd我记得是有package可以进行相互转换的。如果没有记错可能是Matlab的package。希望能帮到你。

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/20/2023 15:23 |
| To | gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds] 您好，这项工作只能使用ply进行推理吗？ (Issue #1) |

使用pcd无法计算出结果

**Comment by ShaneCan** [comment]
> 你好，我具体细节忘了很多。我这个工作只是一个点云对图像的投影和连线的可视化。我是用ply进行处理的。ply和pcd我记得是有package可以进行相互转换的。如果没有记错可能是Matlab的package。希望能帮到你。
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/20/2023 15:23 | | To | gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds ***@***.***> | | Cc | Subscribed ***@***.***> | | Subject | [gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds] 您好，这项工作只能使用ply进行推理吗？ (Issue #1) | 使用pcd无法计算出结果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

非常感谢您及时耐心的回复！您这项工作对我启发很大，我还是想再请教您两个问题：
1.这项工作做的内容是场景流估计吗？因为我刚刚接触这个领域，不太明白您说的只是一个点云对图像的投影和连线的可视化。它跟flownet等算法最终做的是一件事吗？
2.我已经将您的ply文件转换为了pcd文件，但是放入代码中，程序不运行，是代码不支持吗？

非常感谢您不吝赐教，这将对我帮助很大，再次感谢！

**Comment by ShaneCan** [comment]
您在文件中包含了new_0000000007.ply，cut_0000000007.ply，0000000007.ply。他们三者有什么关系呢？是怎么获得的呢？再次感谢您！

**Comment by gpeihong** [comment]
数据都是在kitti官网找的。我忘了new和源数据有什么区别（应该是我为了区分什么来着 但是你姑且将new当成原文件）但是cut是我对源点云数据进行了裁剪segment。因为我需要将点云包含的空间和对应的图像所包含的空间一致。因为原点云包含的空间是大于对应图像包含空间的。此外可能还为了去掉一些离群值。但是在做配准的时候我用的还是原点云，并不是cut。

至于0007 和0008 是我随便取了两帧相邻点云。

只能回忆到这了。祝研究顺利。

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/20/2023 16:21 |
| To | gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds ***@***.***> |
| Cc | ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds] 您好，这项工作只能使用ply进行推理吗？ (Issue #1) |

您在文件中包含了new_0000000007.ply，cut_0000000007.ply，0000000007.ply。他们三者有什么关系呢？是怎么获得的呢？再次感谢您！

**Comment by ShaneCan** [comment]
> 数据都是在kitti官网找的。我忘了new和源数据有什么区别（应该是我为了区分什么来着 但是你姑且将new当成原文件）但是cut是我对源点云数据进行了裁剪segment。因为我需要将点云包含的空间和对应的图像所包含的空间一致。因为原点云包含的空间是大于对应图像包含空间的。此外可能还为了去掉一些离群值。但是在做配准的时候我用的还是原点云，并不是cut。 至于0007 和0008 是我随便取了两帧相邻点云。 只能回忆到这了。祝研究顺利。
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/20/2023 16:21 | | To | gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds ***@***.***> | | Cc | ***@***.***>, Comment ***@***.***> | | Subject | Re: [gpeihong/Image-based-Scene-Flow-Estimation-for-3D-Point-Clouds] 您好，这项工作只能使用ply进行推理吗？ (Issue #1) | 您在文件中包含了new_0000000007.ply，cut_0000000007.ply，0000000007.ply。他们三者有什么关系呢？是怎么获得的呢？再次感谢您！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢您的解答，祝好！
